const ActionTypes = {
  ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  ADD_TODO_FAILURE: "ADD_TODO_FAILURE",

  DELETE_TODO_REQUEST: "DELETE_TODO_REQUEST",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
  DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",

  UPDATE_TODO_REQUEST: "UPDATE_TODO_REQUEST",
  UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
  UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE",

  GET_SINGLE_TODO_REQUEST: "GET_SINGLE_TODO_REQUEST",
  GET_SINGLE_TODO_SUCCESS: "GET_SINGLE_TODO_SUCCESS",
  GET_SINGLE_TODO_FAILURE: "GET_SINGLE_TODO_FAILURE",

  CLEAR_SINGLE_TODO: "CLEAR_SINGLE_TODO",

  GET_ALL_TODOS_REQUEST: "GET_ALL_TODOS_REQUEST",
  GET_ALL_TODOS_SUCCESS: "GET_ALL_TODOS_SUCCESS",
  GET_ALL_TODOS_FAILURE: "GET_ALL_TODOS_FAILURE",
};

export default ActionTypes;
